"""Property test for the rollback primitive.

Generates a sequence of random metadata mutations (add column, change spec, change
sort order, plus optional appends) and asserts that ``restore_pointers`` returns the
table to its captured state for every sequence the strategy produces.

Wall-clock budget per example is large (a few catalog round-trips per mutation), so
we cap ``max_examples`` low and disable hypothesis's slow-test health checks. Five
examples with up to 15 mutations each is enough to exercise interaction effects
between schema/spec/sort-order rotation and snapshot advancement that the
per-scenario tests would otherwise miss.
"""

from __future__ import annotations

import itertools
import uuid
from collections.abc import Iterator

import pyarrow as pa
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from pyiceberg.catalog.rest import RestCatalog
from pyiceberg.schema import Schema
from pyiceberg.transforms import IdentityTransform
from pyiceberg.types import IntegerType, LongType, NestedField, StringType

from cambrian.iceberg import capture, restore_pointers

_ID_SEQUENCE: Iterator[int] = itertools.count(start=1)


def _initial_schema() -> Schema:
    return Schema(
        NestedField(field_id=1, name="id", field_type=LongType(), required=False),
        NestedField(field_id=2, name="name", field_type=StringType(), required=False),
        NestedField(field_id=3, name="value", field_type=IntegerType(), required=False),
    )


def _append_row(table, row_id: int):  # type: ignore[no-untyped-def]
    # PyArrow needs the *current* iceberg schema's columns; we only ever add nullable
    # columns, so a v1 row with NULL fill-ins always lines up. Use the table's
    # current schema's field names rather than hard-coding so dropped columns or
    # renames don't break this helper if the strategy is later extended.
    field_names = [field.name for field in table.schema().fields]
    record: dict[str, int | str | None] = {
        "id": row_id,
        "name": f"row-{row_id}",
        "value": row_id * 10,
    }
    for name in field_names:
        record.setdefault(name, None)
    payload = {k: [record[k]] for k in field_names}
    arrow_fields: list[pa.Field] = []
    for name in field_names:
        if name == "id":
            arrow_fields.append(pa.field("id", pa.int64()))
        elif name == "name":
            arrow_fields.append(pa.field("name", pa.string()))
        else:
            arrow_fields.append(pa.field(name, pa.int32()))
    table.append(pa.table(payload, schema=pa.schema(arrow_fields)))


# Mutation tokens generated by the hypothesis strategy. Each is replayed by the
# test against a live table after capture. The strategy can repeat a mutation kind
# arbitrarily — PyIceberg silently no-ops a duplicate add-partition-field, which
# is the correct property for rollback (any number of repeats restores to the same
# starting state).
_MUTATIONS = st.lists(
    st.sampled_from(["add_col", "spec", "sort", "append"]),
    min_size=5,
    max_size=15,
)


@settings(
    max_examples=5,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)
@given(operations=_MUTATIONS)
def test_restore_pointers_roundtrips_any_mutation_sequence(
    rest_catalog: RestCatalog,
    operations: list[str],
) -> None:
    namespace = f"prop_{uuid.uuid4().hex[:10]}"
    rest_catalog.create_namespace(namespace)
    table_id = (namespace, "t")
    extra_col_counter = itertools.count(start=1)
    try:
        table = rest_catalog.create_table(identifier=table_id, schema=_initial_schema())
        # An initial append guarantees a current_snapshot to anchor the rollback
        # against. The metadata-only no-append case is covered by the per-scenario
        # tests; here we focus on multi-mutation interactions.
        _append_row(table, next(_ID_SEQUENCE))
        table = rest_catalog.load_table(table_id)
        cp = capture(table)
        assert cp.snapshot_id is not None

        for op in operations:
            if op == "add_col":
                col_name = f"extra_{next(extra_col_counter)}"
                with table.update_schema() as us:
                    us.add_column(col_name, IntegerType(), required=False)
            elif op == "spec":
                # PyIceberg disallows duplicate (source_column, transform) pairs even
                # under different partition-field names. Skip the mutation silently if
                # we've already added the identity-on-value partition - the property
                # we care about (rollback restores the same state) is unaffected by
                # whether the mutation was applied N times or once.
                try:
                    with table.update_spec() as usp:
                        usp.add_field(
                            "value",
                            IdentityTransform(),
                            f"value_part_{next(extra_col_counter)}",
                        )
                except ValueError as err:
                    if "Duplicate partition field" not in str(err):
                        raise
            elif op == "sort":
                with table.update_sort_order() as uso:
                    uso.asc("id", IdentityTransform())
            elif op == "append":
                _append_row(table, next(_ID_SEQUENCE))
            else:
                msg = f"unknown mutation kind {op!r}"
                raise AssertionError(msg)
            table = rest_catalog.load_table(table_id)

        current_snap = table.current_snapshot()
        assert current_snap is not None
        restore_pointers(
            table,
            target_snapshot_id=cp.snapshot_id,
            target_schema_id=cp.schema_id,
            target_spec_id=cp.spec_id,
            target_sort_order_id=cp.sort_order_id,
            expected_current_snapshot_id=current_snap.snapshot_id,
        )

        table = rest_catalog.load_table(table_id)
        post = capture(table)
        assert post.snapshot_id == cp.snapshot_id
        assert post.schema_id == cp.schema_id
        assert post.spec_id == cp.spec_id
        assert post.sort_order_id == cp.sort_order_id
    finally:
        try:
            rest_catalog.drop_table(table_id)
        except Exception:
            pass
        try:
            rest_catalog.drop_namespace(namespace)
        except Exception:
            pass
